src/lib.rs

Prevents this panic on launch of the host example:
```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Access', src/lib.rs:51:61
```

Fix crash when device doesn’t have write permission

---

src/lib.rs

As per [documentation](https://www.kernel.org/doc/html/latest/usb/usbip_protocol.html), an `USBIP_CMD_UNLINK` response should return 24 bytes of padding.

Write padding in unlink response

---

src/device.rs
src/lib.rs

Devices presented over usbip should have their descriptors are mirrored in their entirety. This include USB version and bcdDeviceVersion.

Mirror device version and usb version in descriptors

---

src/host.rs

A device should not return more than the maximum transfer size of the endpoint. In my experience, usbip on the client terminates the connection when this condition occurs.

Constrain endpoint writes to maximum buffer size of endpoint.

---

src/lib.rs

Add filter variant to `new_from_host`. 
`new_from_host_with_filter` accepts a callback function where users can perform additional filtering on devices. This is useful for exposing select devices from a host.

new_from_host_with_filter

---

src/device.rs
src/lib.rs

* Moves socket logic for reading out data to the place where socket reads and writes are handled. This neatens up the `handle_urb` interface.
* Parse the setup packet and give to handle_urb.
* Fixes #13, where the number of bytes was not set in the URB transfer response `actual_length` field.

Write byte length on OUT request

---

src/consts.rs

This fixes #20 by correcting the value.
I also added in the `SetAddress` code as I can't think of a good reason why it shouldn't be there and fixed the spelling of `SynchFrame`.

Correct Standard Request Codes

---

Cargo.toml
examples/cdc_acm_serial.rs
examples/hid_keyboard.rs
examples/host.rs
src/lib.rs
src/util.rs

This is an attempt at creating a solution for #16.
~~Using a [tokio barrier](https://docs.rs/tokio/latest/tokio/sync/struct.Barrier.html) and a control flag, the server should be able to wait for all threads to pause, modify the devicelist, and resume all threads. New functions `UsbIpServer::add_device` and `UsbIpServer::remove_device` has been added, and `handler` has been made into `UsbIpServer::handler`, and made public to allow for other implementations of the server loop.~~
Edit: The implementation has changed a lot, ignore the stuff above.
**Summary:**
- Added `UsbIpServer::add_device(UsbDevice)`
- Added `UsbIpServer::remove_device(UsbDevice)`
- Made `handler` public, in order to be able to create custom server loops themselves. This allows the user of the library to create loops …

Add support for modifying devicelist during execution

---

src/cdc.rs
src/device.rs
src/hid.rs
src/host.rs
src/interface.rs
src/lib.rs

Closes #24.
This breaks the API. Since #18 is also breaking, could I ask both to be released under a new major version when they eventually get reviewed and merged?
Also, should we enforce people to conform to the given buffer length by providing a mutable slice and making `handle_urb -> Result<()>`, rather than the comment?

Add `transfer_buffer_length` to `handle_urb`

---

.github/workflows/main.yml
examples/cdc_acm_serial.rs
examples/hid_keyboard.rs
examples/host.rs
src/cdc.rs
src/device.rs
src/hid.rs
src/host.rs
src/lib.rs
src/util.rs

Clippy already seemed to be included in the CI workflow, it was just never executed.

Fix clippy warnings and add clippy to pipeline

---

src/cdc.rs
src/device.rs
src/hid.rs
src/lib.rs
src/usbip_protocol.rs
src/util.rs

This PR splits all byte de/serialization from the handler into its own contained module.
This might seem like a lot of extra boilerplate right now, but I'm planning to create another PR where I'll reuse this logic.
I've also marked all of these items as public API, which might be useful for people using the package only for reading and/or writing packages, rather than the server loop. Network monitoring software similar to wireshark might find this useful.
As a by-product, these things have also been fixed:
- Setup `env_logger` before every test
- Use consistent `path`/`busid` format for both default device and server
- `debug_assert` that `path`/`busid` lengths don't overflow
- Throw proper error message on old USB/IP version
- Send proper USB/IP error on `USBIP_CMD_SUBMIT` with invalid …

Split usbip protocol de/serialization from server handler

---

.github/workflows/main.yml

The pipeline has been updated with the following changes:
- Run all steps in parallell
- Update several of the steps, also [the entirety of actions-rs seems to be unmaintained](https://github.com/actions-rs/toolchain/issues/216)
- Only run coveralls on PRs, to avoid breaking workflows on forks
- Add dependency cache to speed up the builds.
- Remove the benchmarking step, we have no benchmarks
We're still using `action-rs/grcov` which might break at some point as it's using deprecated API functions. I haven't found any good alternatives for this yet. But I think this should at least make less things break whenever the API gets deprecated for good.

Update main workflow with several changes

---

src/lib.rs

This won't fix the root cause of #15 and #30, but it will at least handle any similar errors without the panic.
I think it's safe to assume that a USB device should have device and config descriptors, so there's probably an underlying issue in the macos kernel, libusb or rusb.

Handle rusb device descriptor errors without panic

---

Cargo.toml
src/consts.rs
src/device.rs
src/endpoint.rs
src/hid.rs
src/interface.rs
src/lib.rs
src/setup.rs

Add serde serialization/deserialization for most public types
This PR depends on a1ien/rusb#167 to be complete,

Add serde support

---

src/setup.rs
src/usbip_protocol.rs

After the few past merges, there were some new types that should have serde impls in #19 as well. This PR adds these impls, and makes clippy happy by adding a conditional macro on an import

Fixup serde impls

---

src/lib.rs
src/util.rs

This partly fixes #3.
Changes the busId check to use a null-terminated string comparison.

Fix busId comparions

---

src/usbip_protocol.rs

This PR fixes a critical error in the usbip protocol parser.
From https://docs.kernel.org/usb/usbip_protocol.html (USBIP_CMD_SUBMIT, USBIP_RET_SUBMIT)
> 0x30 - n - transfer_buffer. **If direction is USBIP_DIR_OUT then n equals transfer_buffer_length; otherwise n equals 0**. For ISO transfers the padding between each ISO packets is not transmitted.
> 0x30 - n - transfer_buffer. **If direction is USBIP_DIR_IN then n equals actual_length; otherwise n equals 0**. For ISO transfers the padding between each ISO packets is not transmitted.
Closes #36

usbip_protocol: fix parser bug on cmd_submit and ret_submit

---

src/lib.rs

I have completely misunderstood the intent of `USBIP_CMD_UNLINK` to mean something else than it's supposed to be. In the current implementations, the correct behavior would be close to a no-op, because we handle all requests in a serial fashion (although #34 might provide the possibility of cancelling URBs).
I have removed the test that reflects the misunderstanding. I do not think it's worth writing a new test for the no-op behavior.
@jiegec: I'm not sure how many client libraries actively send these unlink requests, but I think this would warrant a patch release nonetheless. It might be a quite severe regression, rendering the library unusable for many people.
Fixes #39

Fix `USBIP_CMD_UNLINK` behaviour

---

src/device.rs
src/lib.rs

This PR fixes a panic that would happen when the client requests an invalid string index, and rather returns a proper error.
Fixes #41 (although the reason behind the client requesting an invalid string index is still a mystery)

Fix panic on request of invalid string pool index

---

src/device.rs

Most devices don't actually set interface descriptors or manufacturer/product name/serial numbers - instead leaving all those strings to 0, likely to save up on space.
I want to test drivers to make sure they react properly to either missing or presence of string descriptor, so I need to have control over whether a string is there or not.
With this MR, all strings start by being unset, and the various functions to set a string now take an `Option<&str>`, with None meaning 0/no string descriptor.
This is an API-breaking change.

Allow not setting a string descriptor
